
["Config for Configurable Falls"]
	#USES VANILLA WATER TAG
	#Required fall distance for entities to take fall damage in Water! Mod Default : 2.2
	#Range: 0.0 ~ 64.0
	"Water Fall Damage Required Fall Distance" = 2.2
	#USES VANILLA WATER TAG
	#How much fall damage entities will take in 1 block deep water!
	#Value explanation : 1.0 = 100% Fall Damage, 0.0 = 0% Fall Damage, 0.5 = 50% Fall Damage, 0.7 = 70% Fall Damage which is the same as a 30% Fall Damage Reduction
	#Range: 0.0 ~ 1.0
	"1 Block Deep Water Fall Damage Percentage" = 1.0
	#USES VANILLA WATER TAG
	#How much fall damage entities will take in 2 block deep water!
	#Value explanation : 1.0 = 100% Fall Damage, 0.0 = 0% Fall Damage, 0.5 = 50% Fall Damage, 0.7 = 70% Fall Damage which is the same as a 30% Fall Damage Reduction
	#Range: 0.0 ~ 1.0
	"2 Block Deep Water Fall Damage Percentages" = 0.5
	#USES VANILLA WATER TAG
	#How much fall damage entities will take in 3 block deep water!
	#Value explanation : 1.0 = 100% Fall Damage, 0.0 = 0% Fall Damage, 0.5 = 50% Fall Damage, 0.7 = 70% Fall Damage which is the same as a 30% Fall Damage Reduction
	#Range: 0.0 ~ 1.0
	"3 Block Deep Water Fall Damage Percentages" = 0.0
	#USES VANILLA WATER TAG
	#How much fall damage entities will take in 4 block deep water!
	#Value explanation : 1.0 = 100% Fall Damage, 0.0 = 0% Fall Damage, 0.5 = 50% Fall Damage, 0.7 = 70% Fall Damage which is the same as a 30% Fall Damage Reduction
	#Range: 0.0 ~ 1.0
	"4 Block Deep Water Fall Damage Percentages" = 0.0
	#USES VANILLA WATER TAG
	#How much fall damage entities will take in 5 block deep water and more!
	#Value explanation : 1.0 = 100% Fall Damage, 0.0 = 0% Fall Damage, 0.5 = 50% Fall Damage, 0.7 = 70% Fall Damage which is the same as a 30% Fall Damage Reduction
	#Range: 0.0 ~ 1.0
	"5 Block Deep Water Fall Damage Percentages" = 0.0
	#Should Ice Break When fallen on?  Vanilla : false   Mod Default : true
	"Ice Break On Fall" = true
	#Required Fall Distance for ice to break on fall if Ice Break On Fall = true, Jumping of 1 block = 2.1
	#Range: 0.0 ~ 64.0
	"Ice Break Fall Distance" = 2.2
	#Should Snow Break When fallen on?  Vanilla : false   Mod Default : true
	"Snow Break On Fall" = true
	#Required Fall Distance for Snow to break on fall if Snow Break On Fall = true, Jumping of 1 block = 2.1
	#Range: 0.0 ~ 64.0
	"Snow Break Fall Distance" = 2.2
	#Should Snow drop snowballs when broken by entities falling on it? Mod Default : false  *Requires Snow Break On Fall to be set to true
	"Snow Drops Snowballs When Broken By Entities Falling On It" = false
	#Should Glass Break When fallen on? (Includes Stained Glass && Tinted Glass) Vanilla : false   Mod Default : true
	"Glass Break On Fall" = true
	#Should Tinted Glass drop when broken by entities falling on it? Mod Default : true  *Requires Glass Break On Fall to be set to true *If any other mods adds glass drops, glass and stained glass will drop the drops added by that mod when its set to true
	"Tinted Glass Drops Tinted Glass When Broken By Entities Falling On It" = true
	#Required Fall Distance for glass to break on fall if Glass Break On Fall = true, Jumping of 1 block = 2.1
	#Range: 0.0 ~ 64.0
	"Glass Break Fall Distance" = 2.2
	#Should Glass Pane Break When fallen on? (Includes Stained Glass Pane) Vanilla : false   Mod Default : true
	"Glass Pane Break On Fall" = true
	#Required Fall Distance for glass pane to break on fall if Glass Pane Break On Fall = true, Jumping of 1 block = 2.1
	#Range: 0.0 ~ 64.0
	"Glass Pane Break Fall Distance" = 2.2
	#How much fall damage entities will take when they fall on Hay Bales.  Vanilla : 0.2. 0.2 = 20% fall damage which is the same as a 80% fall damage reduction
	#Range: 0.0 ~ 1.0
	"Hay Bale Fall Damage Percentage" = 0.2
	#Should Grass Break When fallen on?  Vanilla : false   Mod Default : true
	"Grass Break On Fall" = true
	#Required Fall Distance for Grass to break on fall if Grass Break On Fall = true, Jumping of 1 block = 2.1
	#Range: 0.0 ~ 64.0
	"Grass Break Fall Distance" = 2.2
	#Should Grass have a chance to drop seeds when broken by entities falling on it? Mod Default : true  *Requires Grass Break On Fall to be set to true
	"Grass Has A Chance To Drop Seeds When Broken By Entities Falling On It" = true
	#Should Grass turn to dirt when fallen on by an entity?  Mod Default : true
	"Grass Turns To Dirt When Fallen On" = true
	#Required Fall Distance for Grass to turn to Dirt if Grass Turns To Dirt When Fallen On = true  Mod Default : 2.9    Jumping of 1 block = 2.1
	#Range: 0.0 ~ 64.0
	"Grass Turns To Dirt Fall Distance" = 2.9
	#Should Tall Grass Break When fallen on?  Vanilla : false   Mod Default : true
	"Tall Grass Break On Fall" = true
	#Required Fall Distance for Tall Grass to break on fall if Tall Grass Break On Fall = true, Jumping of 1 block = 2.1
	#Range: 0.0 ~ 64.0
	"Tall Grass Break Fall Distance" = 2.9
	#Should Tall Grass have a chance to drop seeds when broken by entities falling on it? Mod Default : true  *Requires Tall Grass Break On Fall to be set to true
	"Tall Grass Has A Chance To Drop Seeds When Broken By Entities Falling On It" = true
	#Required Fall Distance for Blocks that have the #fragile tag to break on fall, Jumping of 1 block = 2.1
	#Range: 0.0 ~ 64.0
	"Blocks With #fragile Required Fall Distance For Block To Break" = 2.2
	#Should Blocks that have the #fragile tag drop their block drops Mod Default : true 
	"Blocks With #fragile tag drop loot" = true
	#Should Suspicious Blocks Break When fallen on?  Vanilla : false   Mod Default : true
	"Suspicious Blocks Break On Fall" = true
	#Required Fall Distance for suspicious blocks to break on fall if Suspicious Blocks Break On Fall = true, Jumping of 1 block = 2.1
	#Range: 0.0 ~ 64.0
	"Suspicious Blocks Break Fall Distance" = 2.2
	#Should Melon Explode Into Melon Slices When fallen on?  Vanilla : false   Mod Default : true
	"Melon Explode Into Melon Slices On Fall" = true
	#Required Fall Distance for melon to explode on fall if Melon Explode Into Melon Slices On Fall = true, Jumping of 1 block = 2.1
	#Range: 0.0 ~ 64.0
	"Melon Explode Into Melon Slices Fall Distance" = 2.2
	#Should Leaves Break When fallen on?  Vanilla & Mod Default : false
	"Leaves Break On Fall" = false
	#Required Fall Distance for Leaves to break on fall if Leaves Break On Fall = true, Jumping of 1 block = 2.1
	#Range: 0.0 ~ 64.0
	"Leaves Break Fall Distance" = 2.2
	#Should Leaves drop apples, saplings & sticks when broken by entities falling on it? Mod Default : false  *Requires Leaves Break On Fall to be set to true
	"Leaves Drops Apples and Saplings and Sticks When Broken By Entities Falling On It" = false

