#allows the user to right click harvest crops
rightClickHarvest = true
#allows the user to disable salt generation in the world, default is false
disableSaltGeneration = false

#Croptopia tree generation
[worldGeneration]

	#Settings for orange_tree_configured
	[worldGeneration.orange_tree_configured]
		biomes = ["minecraft:plains", "biomesoplenty:woodland", "biomesoplenty:pumpkin_patch", "byg:orchard", "minecraft:sunflower_plains", "biomesoplenty:mystic_grove", "minecraft:flower_forest", "minecraft:forest", "biomesoplenty:mediterranean_forest", "biomesoplenty:seasonal_forest", "minecraft:windswept_forest", "byg:red_oak_forest", "byg:aspen_forest", "biomesoplenty:redwood_forest", "biomesoplenty:bamboo_grove", "biomesoplenty:seasonal_orchard"]

	#Settings for dragon_fruit_tree_configured
	[worldGeneration.dragon_fruit_tree_configured]
		biomes = ["biomesoplenty:rainforest", "biomesoplenty:rocky_rainforest", "byg:tropical_rainforest", "minecraft:sparse_jungle", "biomesoplenty:floodplain", "byg:crag_gardens", "byg:tropical_islands", "minecraft:jungle", "biomesoplenty:fungal_jungle"]

	#Settings for kumquat_tree_configured
	[worldGeneration.kumquat_tree_configured]
		biomes = ["biomesoplenty:rainforest", "biomesoplenty:rocky_rainforest", "byg:tropical_rainforest", "minecraft:sparse_jungle", "biomesoplenty:floodplain", "byg:crag_gardens", "byg:tropical_islands", "minecraft:jungle", "biomesoplenty:fungal_jungle"]

	#Settings for banana_tree_configured
	[worldGeneration.banana_tree_configured]
		biomes = ["biomesoplenty:rainforest", "biomesoplenty:rocky_rainforest", "byg:tropical_rainforest", "minecraft:sparse_jungle", "biomesoplenty:floodplain", "byg:crag_gardens", "byg:tropical_islands", "minecraft:jungle", "biomesoplenty:fungal_jungle"]

	#Settings for plum_tree_configured
	[worldGeneration.plum_tree_configured]
		biomes = ["byg:autumnal_taiga", "biomesoplenty:woodland", "biomesoplenty:pumpkin_patch", "byg:jacaranda_forest", "byg:orchard", "biomesoplenty:mystic_grove", "minecraft:flower_forest", "minecraft:forest", "biomesoplenty:mediterranean_forest", "biomesoplenty:seasonal_forest", "minecraft:windswept_forest", "byg:red_oak_forest", "byg:aspen_forest", "biomesoplenty:redwood_forest", "biomesoplenty:bamboo_grove", "byg:autumnal_forest", "biomesoplenty:seasonal_orchard"]

	#Settings for date_tree_configured
	[worldGeneration.date_tree_configured]
		biomes = ["biomesoplenty:rainforest", "biomesoplenty:rocky_rainforest", "byg:tropical_rainforest", "minecraft:sparse_jungle", "biomesoplenty:floodplain", "byg:crag_gardens", "byg:tropical_islands", "minecraft:jungle", "biomesoplenty:fungal_jungle"]

	#Settings for cashew_tree_configured
	[worldGeneration.cashew_tree_configured]
		biomes = ["byg:ebony_woods", "byg:dacite_ridges", "byg:maple_taiga", "minecraft:dark_forest", "biomesoplenty:highland", "byg:weeping_witch_forest", "byg:twilight_meadow"]

	#Settings for mango_tree_configured
	[worldGeneration.mango_tree_configured]
		biomes = ["biomesoplenty:rainforest", "biomesoplenty:rocky_rainforest", "byg:tropical_rainforest", "minecraft:sparse_jungle", "biomesoplenty:floodplain", "byg:crag_gardens", "byg:tropical_islands", "minecraft:jungle", "biomesoplenty:fungal_jungle"]

	#Settings for coconut_tree_configured
	[worldGeneration.coconut_tree_configured]
		biomes = ["biomesoplenty:rainforest", "biomesoplenty:rocky_rainforest", "byg:tropical_rainforest", "minecraft:sparse_jungle", "biomesoplenty:floodplain", "byg:crag_gardens", "byg:tropical_islands", "minecraft:jungle", "biomesoplenty:fungal_jungle"]

	#Settings for apricot_tree_configured
	[worldGeneration.apricot_tree_configured]
		biomes = ["biomesoplenty:woodland", "biomesoplenty:pumpkin_patch", "byg:orchard", "biomesoplenty:mystic_grove", "minecraft:flower_forest", "minecraft:forest", "biomesoplenty:mediterranean_forest", "biomesoplenty:seasonal_forest", "minecraft:windswept_forest", "byg:red_oak_forest", "byg:aspen_forest", "biomesoplenty:redwood_forest", "biomesoplenty:bamboo_grove", "biomesoplenty:seasonal_orchard"]

	#Settings for nutmeg_tree_configured
	[worldGeneration.nutmeg_tree_configured]
		biomes = ["biomesoplenty:rainforest", "biomesoplenty:rocky_rainforest", "byg:tropical_rainforest", "minecraft:sparse_jungle", "biomesoplenty:floodplain", "byg:crag_gardens", "byg:tropical_islands", "minecraft:jungle", "biomesoplenty:fungal_jungle"]

	#Settings for persimmon_tree_configured
	[worldGeneration.persimmon_tree_configured]
		biomes = ["byg:autumnal_taiga", "biomesoplenty:woodland", "biomesoplenty:pumpkin_patch", "byg:jacaranda_forest", "byg:orchard", "biomesoplenty:mystic_grove", "minecraft:flower_forest", "minecraft:forest", "biomesoplenty:mediterranean_forest", "biomesoplenty:seasonal_forest", "minecraft:windswept_forest", "byg:red_oak_forest", "byg:aspen_forest", "biomesoplenty:redwood_forest", "biomesoplenty:bamboo_grove", "byg:autumnal_forest", "biomesoplenty:seasonal_orchard"]

	#Settings for almond_tree_configured
	[worldGeneration.almond_tree_configured]
		biomes = ["byg:ebony_woods", "byg:dacite_ridges", "byg:maple_taiga", "minecraft:dark_forest", "biomesoplenty:highland", "byg:weeping_witch_forest", "byg:twilight_meadow"]

	#Settings for avocado_tree_configured
	[worldGeneration.avocado_tree_configured]
		biomes = ["biomesoplenty:woodland", "biomesoplenty:pumpkin_patch", "byg:orchard", "biomesoplenty:mystic_grove", "minecraft:flower_forest", "minecraft:forest", "biomesoplenty:mediterranean_forest", "biomesoplenty:seasonal_forest", "minecraft:windswept_forest", "byg:red_oak_forest", "byg:aspen_forest", "biomesoplenty:redwood_forest", "biomesoplenty:bamboo_grove", "biomesoplenty:seasonal_orchard"]

	#Settings for fig_tree_configured
	[worldGeneration.fig_tree_configured]
		biomes = ["biomesoplenty:rainforest", "biomesoplenty:rocky_rainforest", "byg:tropical_rainforest", "minecraft:sparse_jungle", "biomesoplenty:floodplain", "byg:crag_gardens", "byg:tropical_islands", "minecraft:jungle", "biomesoplenty:fungal_jungle"]

	#Settings for cinnamon_tree_configured
	[worldGeneration.cinnamon_tree_configured]
		biomes = ["biomesoplenty:rainforest", "biomesoplenty:rocky_rainforest", "biomesoplenty:bog", "byg:tropical_rainforest", "minecraft:sparse_jungle", "biomesoplenty:marsh", "byg:tropical_islands", "minecraft:jungle", "byg:white_mangrove_marshes", "byg:cypress_swamplands", "biomesoplenty:floodplain", "byg:temperate_rainforest", "byg:crag_gardens", "biomesoplenty:bayou", "biomesoplenty:fungal_jungle"]

	#Settings for peach_tree_configured
	[worldGeneration.peach_tree_configured]
		biomes = ["minecraft:plains", "minecraft:sunflower_plains"]

	#Settings for apple_tree_configured
	[worldGeneration.apple_tree_configured]
		biomes = ["minecraft:plains", "biomesoplenty:bog", "byg:coniferous_forest", "byg:prairie", "biomesoplenty:fir_clearing", "biomesoplenty:tundra", "minecraft:sunflower_plains", "biomesoplenty:maples_woods", "biomesoplenty:field"]

	#Settings for pear_tree_configured
	[worldGeneration.pear_tree_configured]
		biomes = ["byg:autumnal_taiga", "biomesoplenty:woodland", "biomesoplenty:pumpkin_patch", "byg:jacaranda_forest", "byg:orchard", "biomesoplenty:mystic_grove", "minecraft:flower_forest", "minecraft:forest", "biomesoplenty:mediterranean_forest", "biomesoplenty:seasonal_forest", "minecraft:windswept_forest", "byg:red_oak_forest", "byg:aspen_forest", "biomesoplenty:redwood_forest", "biomesoplenty:bamboo_grove", "byg:autumnal_forest", "biomesoplenty:seasonal_orchard"]

	#Settings for grapefruit_tree_configured
	[worldGeneration.grapefruit_tree_configured]
		biomes = ["biomesoplenty:rainforest", "biomesoplenty:rocky_rainforest", "byg:tropical_rainforest", "minecraft:sparse_jungle", "biomesoplenty:floodplain", "byg:crag_gardens", "byg:tropical_islands", "minecraft:jungle", "biomesoplenty:fungal_jungle"]

	#Settings for star_fruit_tree_configured
	[worldGeneration.star_fruit_tree_configured]
		biomes = ["biomesoplenty:woodland", "biomesoplenty:pumpkin_patch", "byg:orchard", "biomesoplenty:mystic_grove", "minecraft:flower_forest", "minecraft:forest", "biomesoplenty:mediterranean_forest", "biomesoplenty:seasonal_forest", "minecraft:windswept_forest", "byg:red_oak_forest", "byg:aspen_forest", "biomesoplenty:redwood_forest", "biomesoplenty:bamboo_grove", "biomesoplenty:seasonal_orchard"]

	#Settings for nectarine_tree_configured
	[worldGeneration.nectarine_tree_configured]
		biomes = ["biomesoplenty:woodland", "biomesoplenty:pumpkin_patch", "byg:orchard", "biomesoplenty:mystic_grove", "minecraft:flower_forest", "minecraft:forest", "biomesoplenty:mediterranean_forest", "biomesoplenty:seasonal_forest", "minecraft:windswept_forest", "byg:red_oak_forest", "byg:aspen_forest", "biomesoplenty:redwood_forest", "biomesoplenty:bamboo_grove", "biomesoplenty:seasonal_orchard"]

	#Settings for lemon_tree_configured
	[worldGeneration.lemon_tree_configured]
		biomes = ["biomesoplenty:woodland", "biomesoplenty:pumpkin_patch", "byg:orchard", "biomesoplenty:mystic_grove", "minecraft:flower_forest", "minecraft:forest", "biomesoplenty:mediterranean_forest", "biomesoplenty:seasonal_forest", "minecraft:windswept_forest", "byg:red_oak_forest", "byg:aspen_forest", "biomesoplenty:redwood_forest", "biomesoplenty:bamboo_grove", "biomesoplenty:seasonal_orchard"]

	#Settings for cherry_tree_configured
	[worldGeneration.cherry_tree_configured]
		biomes = ["biomesoplenty:woodland", "biomesoplenty:pumpkin_patch", "biomesoplenty:cherry_blossom_grove", "byg:orchard", "biomesoplenty:mystic_grove", "minecraft:flower_forest", "minecraft:forest", "biomesoplenty:mediterranean_forest", "biomesoplenty:seasonal_forest", "minecraft:windswept_forest", "byg:cherry_blossom_forest", "byg:red_oak_forest", "byg:aspen_forest", "biomesoplenty:redwood_forest", "biomesoplenty:bamboo_grove", "biomesoplenty:seasonal_orchard"]

	#Settings for lime_tree_configured
	[worldGeneration.lime_tree_configured]
		biomes = ["biomesoplenty:woodland", "biomesoplenty:pumpkin_patch", "byg:orchard", "biomesoplenty:mystic_grove", "minecraft:flower_forest", "minecraft:forest", "biomesoplenty:mediterranean_forest", "biomesoplenty:seasonal_forest", "minecraft:windswept_forest", "byg:red_oak_forest", "byg:aspen_forest", "biomesoplenty:redwood_forest", "biomesoplenty:bamboo_grove", "biomesoplenty:seasonal_orchard"]

	#Settings for pecan_tree_configured
	[worldGeneration.pecan_tree_configured]
		biomes = ["byg:ebony_woods", "byg:dacite_ridges", "byg:maple_taiga", "minecraft:dark_forest", "biomesoplenty:highland", "byg:weeping_witch_forest", "byg:twilight_meadow"]

	#Settings for walnut_tree_configured
	[worldGeneration.walnut_tree_configured]
		biomes = ["byg:ebony_woods", "byg:dacite_ridges", "byg:maple_taiga", "minecraft:dark_forest", "biomesoplenty:highland", "byg:weeping_witch_forest", "byg:twilight_meadow"]

