
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true
	#Creates a debug folder inside your instance directory where all the dynamically generated resources will be saved
	save_debug_resources = false
	#Don't touch unless you are told to
	debug_packet = false
	#Sends a packet to verify all dependencies mod versions are the same on connect. DIsable if it causes issues
	mod_version_check_packet = true

	[general.tooltips]
		#Enabled tooltips showing which mod an EC item is from
		mod_origin_enabled = true
		#Only show on advanced settings
		show_on_advanced_tooltips = false
		#Enabled tooltips showing which block type an EC item is made from
		block_type_enabled = true

	#Disables certain types
	[general.types]

		[general.types.wood_type]

			[general.types.wood_type.mysticsbiomes]
				strawberry = true
				cherry = true
				jacaranda = true
				maple = true
				peach = true
				sea_foam = true

			[general.types.wood_type.deserts_and_dunes]
				fan_palm = true
				yucca = true
				joshua = true
				palo_verde = true
				boojum = true

			[general.types.wood_type.enlightened_end]
				indigo = true
				cerulean = true

			[general.types.wood_type.aether]
				skyroot = true

			[general.types.wood_type.deeperdarker]
				echo = true

			[general.types.wood_type.alexscaves]
				pewen = true
				thornwood = true

			[general.types.wood_type.ad_astra]
				aeronos = true
				strophar = true
				glacian = true

			[general.types.wood_type.betterarcheology]
				rotten = true

			[general.types.wood_type.deep_aether]
				roseroot = true
				yagroot = true
				cruderoot = true
				conberry = true
				sunroot = true

			[general.types.wood_type.forbidden_arcanus]
				aurum = true
				edelwood = true

			[general.types.wood_type.meadow]
				pine = true

			[general.types.wood_type.beachparty]
				palm = true

			[general.types.wood_type.habitat]
				fairy_ring_mushroom = true

			[general.types.wood_type.ecologics]
				flowering_azalea = true
				azalea = true
				coconut = true
				walnut = true

			[general.types.wood_type.snifferplus]
				stone_pine = true

			[general.types.wood_type.born_in_chaos_v1]
				scorched = true

			[general.types.wood_type.various_world]
				crystalic_oak = true
				sakura = true
				sculk = true

			[general.types.wood_type.bloomingnature]
				larch = true
				baobab = true
				swamp_oak = true
				aspen = true
				fir = true
				swamp_cypress = true
				ebony = true
				chestnut = true
				fan_palm = true

			[general.types.wood_type.tropicraft]
				mahogany = true
				palm = true
				mangrove = true

			[general.types.wood_type.blue_skies]
				crystallized = true
				bluebright = true
				starlit = true
				frostbright = true
				lunar = true
				dusk = true
				maple = true
				comet = true

			[general.types.wood_type.quark]
				azalea = true
				ancient = true
				blossom = true

			[general.types.wood_type.truedarkness]
				darkness_spruce = true
				cyan = true
				fake = true
				glow = true

			[general.types.wood_type.undergarden]
				smogstem = true
				wigglewood = true
				grongle = true

			[general.types.wood_type.theabyss]
				blaru = true
				jungle = true
				slimed = true
				frozen = true
				vigilant = true
				rena = true
				luna = true

			[general.types.wood_type.twilightforest]
				twilight_oak = true
				canopy = true
				mangrove = true
				dark = true
				time = true
				transformation = true
				mining = true
				sorting = true

			[general.types.wood_type.regions_unexplored]
				alpha = true
				baobab = true
				blackwood = true
				blue_bioshroom = true
				brimwood = true
				cobalt = true
				cypress = true
				dead = true
				eucalyptus = true
				green_bioshroom = true
				joshua = true
				kapok = true
				larch = true
				magnolia = true
				maple = true
				mauve = true
				palm = true
				pine = true
				pink_bioshroom = true
				redwood = true
				socotra = true
				willow = true
				yellow_bioshroom = true

			[general.types.wood_type.organics]
				hoaky = true

			[general.types.wood_type.pizzacraft]
				olive = true

			[general.types.wood_type.cataclysm]
				chorus = true

		[general.types.leaves_type]

			[general.types.leaves_type.deserts_and_dunes]
				palo_verde = true
				boojum = true

			[general.types.leaves_type.enhancedfarming]
				apple = true
				lemon = true
				orange = true
				cherry = true
				pear = true
				banana = true
				avocado = true
				mango = true
				olive = true

			[general.types.leaves_type.croptopia]
				cinnamon = true

			[general.types.leaves_type.aether]
				skyroot = true
				golden_oak = true
				crystal = true
				crystal_fruit = true
				holiday = true
				decorated_holiday = true

			[general.types.leaves_type.biome_backlog]
				baobab = true
				palm = true

			[general.types.leaves_type.deeperdarker]
				echo = true

			[general.types.leaves_type.alexscaves]
				ancient = true

			[general.types.leaves_type.ad_astra]
				glacian = true

			[general.types.leaves_type.vinery]
				grapevine = true
				apple = true
				dark_cherry = true

			[general.types.leaves_type.meadow]
				pine = true

			[general.types.leaves_type.deep_aether]
				roseroot = true
				flowering_roseroot = true
				blue_roseroot = true
				flowering_blue_roseroot = true
				yagroot = true
				cruderoot = true
				conberry = true
				sunroot = true

			[general.types.leaves_type.gaiadimension]
				pink_agate = true
				blue_agate = true
				green_agate = true
				purple_agate = true
				fossilized = true
				corrupted = true
				burnt_agate = true
				fire_agate = true
				aura = true
				golden = true

			[general.types.leaves_type.forbidden_arcanus]
				aurum = true
				nuggety_aurum = true

			[general.types.leaves_type.simplefarming]
				apple = true
				apricot = true
				banana = true
				cherry = true
				mango = true
				olive = true
				orange = true
				pear = true
				plum = true

			[general.types.leaves_type.beachparty]
				palm = true

			[general.types.leaves_type.ecologics]
				coconut = true
				walnut = true

			[general.types.leaves_type.fruitsdelight]
				pear = true
				hawberry = true
				lychee = true
				mango = true
				persimmon = true
				peach = true
				orange = true
				apple = true
				mangosteen = true
				bayberry = true
				kiwi = true
				fig = true
				durian = true

			[general.types.leaves_type.snifferplus]
				stone_pine = true

			[general.types.leaves_type.various_world]
				sakura = true
				sculk = true

			[general.types.leaves_type.bloomingnature]
				larch = true
				baobab = true
				orange = true
				swamp_oak = true
				aspen = true
				swamp_cypress = true
				ebony = true
				chestnut = true
				fan_palm = true

			[general.types.leaves_type.tropicraft]
				mahogany = true
				palm = true
				kapok = true
				fruit = true
				grapefruit = true
				lemon = true
				lime = true
				orange = true
				papaya = true
				white_flowering = true
				red_flowering = true
				blue_flowering = true
				purple_flowering = true
				yellow_flowering = true
				red_mangrove = true
				tall_mangrove = true
				tea_mangrove = true
				black_mangrove = true

			[general.types.leaves_type.blue_skies]
				crystallized = true
				crescent_fruit = true
				bluebright = true
				starlit = true
				frostbright = true
				lunar = true
				dusk = true
				maple = true
				comet = true

			[general.types.leaves_type.regions_unexplored]
				bamboo = true
				golden_larch = true
				alpha = true
				apple_oak = true
				baobab = true
				blackwood = true
				magnolia = true
				cypress = true
				dead = true
				dead_pine = true
				eucalyptus = true
				flowering = true
				kapok = true
				larch = true
				maple = true
				mauve = true
				orange_maple = true
				palm = true
				pine = true
				blue_magnolia = true
				pink_magnolia = true
				redwood = true
				red_maple = true
				brimwood = true
				enchanted_birch = true
				small_oak = true
				silver_birch = true
				socotra = true
				white_magnolia = true
				willow = true
				ashen = true

			[general.types.leaves_type.twilightforest]
				beanstalk = true
				thorn = true
				twilight_oak = true
				canopy = true
				mangrove = true
				dark = true
				rainbow_oak = true
				time = true
				transformation = true
				mining = true
				sorting = true

			[general.types.leaves_type.truedarkness]
				darkness_spruce = true
				grape_azalea = true
				bushy_grape_azalea = true

			[general.types.leaves_type.twilightdelight]
				ironwood = true

			[general.types.leaves_type.undergarden]
				smogstem = true
				wigglewood = true
				grongle = true

			[general.types.leaves_type.quark]
				ancient = true
				blue_blossom = true
				lavender_blossom = true
				orange_blossom = true
				yellow_blossom = true
				red_blossom = true

			[general.types.leaves_type.organics]
				hoaky = true

			[general.types.leaves_type.atlantis]
				palm = true

			[general.types.leaves_type.pizzacraft]
				olive = true
				fruit_olive = true

		[general.types.cake]

			[general.types.cake.mysticsbiomes]
				strawberry_cake = true
				pink_frosted_cake = true
				orange_frosted_cake = true
				yellow_frosted_cake = true
				lime_frosted_cake = true
				cyan_frosted_cake = true
				purple_frosted_cake = true

			[general.types.cake.blue_skies]
				comet_berry_pie = true

			[general.types.cake.simplefarming]
				chocolate_cake = true
				sprinkle_cake = true
				cheese_wheel = true

	#Disables specific entries
	[general.entries]

		[general.entries.wood_type]

			[general.entries.wood_type.decorative_blocks]
				beam = true
				support = true
				seat = true
				palisade = true

			[general.entries.wood_type.hearth_and_home]
				sanded_wood = true
				lattice = true
				parquet = true
				vertical_trim = true
				trim = true

			[general.entries.wood_type.mcwbridges]
				bridge_pier = true
				rope_bridge_stair = true
				log_bridge_stair = true
				rail_bridge = true
				rope_bridge = true
				log_bridge_middle = true

			[general.entries.wood_type.create]
				window_pane = true
				window = true

			[general.entries.wood_type.farmersdelight]
				cabinet = true

			[general.entries.wood_type.twilightforest]
				hollow_log_horizontal = true
				hollow_log_vertical = true
				banister = true
				hollow_log_climbable = true

			[general.entries.wood_type.quark]
				hollow_log = true
				vertical_planks = true
				post = true
				trapped_chest = true
				bookshelf = true
				chest = true
				stripped_post = true
				ladder = true

			[general.entries.wood_type.regions_unexplored]
				branch = true

		[general.entries.leaves_type]

			[general.entries.leaves_type.quark]
				hedge = true
				leaf_carpet = true

